# general settings
name: Uformer
model_type: SRModel
scale: 1
num_gpu: auto # auto: can infer from your visible devices automatically. official: 8 GPUs
manual_seed: 0
find_unused_parameters: true

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: HDR_Dataset
    dataroot: datasets/train
    max_others: 4
    geometric_augs: true

    filename_tmpl: "{}"
    io_backend:
      type: disk

    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    gt_size: 256 # Max patch size for progressive training
    # data loader
    use_shuffle: true
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # Uncomment these for validation
  val:
    name: ValSet
    type: HDR_Dataset
    gt_size: 256
    dataroot: datasets/train
    io_backend:
      type: disk

# network structures
network_g:
  type: Uformer
  img_ch: 15
  output_ch: 3

# path
path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999

  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# Uncomment these for validation
# validation settings
val:
  val_freq: !!float 5e3
  save_img: False

  metrics:
    psnr: # metric name
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
